const translateLanguages = [
  { c: 'sq', l: 'Albanian' },
  { c: 'ar', l: 'Arabic' },
  { c: 'hy', l: 'Armenian' },
  { c: 'az', l: 'Azerbaijani' },
  { c: 'be', l: 'Belarusian' },
  { c: 'bs', l: 'Bosnian' },
  { c: 'bg', l: 'Bulgarian' },
  { c: 'ca', l: 'Catalan' },
  { c: 'zh', l: 'Chinese' },
  { c: 'hr', l: 'Croatian' },
  { c: 'cs', l: 'Czech' },
  { c: 'da', l: 'Danish' },
  { c: 'nl', l: 'Dutch' },
  { c: 'en', l: 'English', selected: true },
  { c: 'et', l: 'Estonian' },
  { c: 'fi', l: 'Finnish' },
  { c: 'fr', l: 'French' },
  { c: 'ka', l: 'Georgian' },
  { c: 'de', l: 'German' },
  { c: 'el', l: 'Greek' },
  { c: 'he', l: 'Hebrew' },
  { c: 'hu', l: 'Hungarian' },
  { c: 'is', l: 'Icelandic' },
  { c: 'id', l: 'Indonesian' },
  { c: 'it', l: 'Italian' },
  { c: 'ja', l: 'Japanese' },
  { c: 'kk', l: 'Kazakh' },
  { c: 'ky', l: 'Kirghiz' },
  { c: 'ko', l: 'Korean' },
  { c: 'lv', l: 'Latvian' },
  { c: 'lt', l: 'Lithuanian' },
  { c: 'mk', l: 'Macedonian' },
  { c: 'ms', l: 'Malay' },
  { c: 'mt', l: 'Maltese' },
  { c: 'no', l: 'Norwegian' },
  { c: 'fa', l: 'Persian' },
  { c: 'pl', l: 'Polish' },
  { c: 'pt', l: 'Portuguese' },
  { c: 'ro', l: 'Romanian' },
  { c: 'ru', l: 'Russian' },
  { c: 'sr', l: 'Serbian' },
  { c: 'sk', l: 'Slovak' },
  { c: 'sl', l: 'Slovenian' },
  { c: 'es', l: 'Spanish' },
  { c: 'sv', l: 'Swedish' },
  { c: 'tg', l: 'Tajik' },
  { c: 'tt', l: 'Tatar' },
  { c: 'th', l: 'Thai' },
  { c: 'tr', l: 'Turkish' },
  { c: 'uk', l: 'Ukrainian' },
  { c: 'vi', l: 'Vietnamese' }
];

export default translateLanguages;
